kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-cloud
rules:
- apiGroups: [""]
  resources: ["services", "pods", "configmaps", "endpoints"]
  verbs: ["get", "watch", "list"]